server:
  port: 8082

spring:
  application:
    name: store-proximity-service
  kafka:
    consumer:
      max-poll-records: 1
  data:
    mongodb:
      host: localhost
      port: 27017

feign:
  client:
    config:
      order-service:
        name: order-service
        url: http://localhost:8083
      courier-service:
        name: courier-service
        url: http://localhost:8081

kafka:
  groupId : courierLocation
  topic:
    courierLocation: courier-location
  address: localhost:9092

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"
